from setuptools import setup, find_packages

setup(
    name="episodic",
    version="0.5.0",
    packages=find_packages(),
    install_requires=[
        "typer>=0.9.0",
        "rich>=13.0.0", 
        "prompt_toolkit>=3.0.0",
        "click>=8.0.0",
        "litellm>=1.0.0",
        "openai>=1.0.0",
        "networkx>=3.0",
        "flask>=3.0.0",
        "plotly>=5.0.0",
        "pygments>=2.0.0",
        "numpy>=1.20.0",
        "pywebview>=4.0.0",
        "python-dotenv>=1.0.0",
        "requests>=2.25.0",
        "aiohttp>=3.8.0",
    ],
    extras_require={
        "rag": ["chromadb>=0.4.0", "sentence-transformers>=2.0.0"],
        "web": ["beautifulsoup4>=4.0.0", "httpx>=0.24.0"],
        "ml": ["scikit-learn>=1.0.0", "nltk>=3.8.0"],
        "pdf": ["pypdf>=3.0.0"],
        "dev": ["pytest>=7.0.0", "black>=23.0.0", "flake8>=6.0.0", "mypy>=1.0.0"],
        "all": [
            "chromadb>=0.4.0",
            "sentence-transformers>=2.0.0",
            "beautifulsoup4>=4.0.0",
            "httpx>=0.24.0",
            "scikit-learn>=1.0.0",
            "nltk>=3.8.0",
            "pypdf>=3.0.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "episodic=episodic.__main__:main",
        ],
    },
    author="Michael H. Coen",
    author_email="mhcoen@gmail.com",
    description="A conversational memory system that creates persistent, navigable conversations with LLMs",
    keywords="episodic, llm, conversation, memory, rag, ai, chatbot",
    url="https://github.com/mhcoen/episodic",
    license="Apache-2.0",
    python_requires=">=3.8",
)
